version: "3.9"

services:
  backend:
    build: ./backend
    container_name: sentiment_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/model:/app/model
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: sentiment_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - app-network

  # Optional MongoDB Service
  mongo:
    image: mongo:6
    container_name: sentiment_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
